"""1.0st migrations

Revision ID: 467fd5873dac
Revises: 
Create Date: 2026-10-04 19:12:50.259994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467fd5873dac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    sa.Enum('pc', 'dz', 'pk', 'box', 'ctn', 'plt', 'mg', 'g', 'kg', 'oz', 'lb', 't', 'ml', 'l', 'fl oz', 'gal', 'mm', 'cm', 'm', 'in', 'ft', name='unit_enum').create(bind=op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'formal_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('items', 'base_unit',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('pc', 'dz', 'pk', 'box', 'ctn', 'plt', 'mg', 'g', 'kg', 'oz', 'lb', 't', 'ml', 'l', 'fl oz', 'gal', 'mm', 'cm', 'm', 'in', 'ft', name='unit_enum'),
               existing_nullable=False, postgresql_using='base_unit::unit_enum',)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'base_unit',
               existing_type=sa.Enum('pc', 'dz', 'pk', 'box', 'ctn', 'plt', 'mg', 'g', 'kg', 'oz', 'lb', 't', 'ml', 'l', 'fl oz', 'gal', 'mm', 'cm', 'm', 'in', 'ft', name='unit_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('items', 'formal_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
