"""1.1st migrations

Revision ID: 65014464351c
Revises: 467fd5873dac
Create Date: 2026-10-04 21:14:56.094933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65014464351c'
down_revision: Union[str, Sequence[str], None] = '467fd5873dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_variant',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sku_name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_items_variant_uid'), 'items_variant', ['uid'], unique=False)
    op.add_column('items', sa.Column('variant_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'items', 'items_variant', ['variant_uid'], ['uid'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'variant_uid')
    op.drop_index(op.f('ix_items_variant_uid'), table_name='items_variant')
    op.drop_table('items_variant')
    # ### end Alembic commands ###
